name: Primer Primitives
on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Rebuild node-sass
        run: npm rebuild node-sass

      - name: Publish to the npm registry
        uses: "primer/publish@v2.0.0"
        with:
          args: "-- --unsafe-perm --allow-same-version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
